/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorSlugRouteImport } from './routes/sector.$slug'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorSlugRoute = SectorSlugRouteImport.update({
  id: '/sector/$slug',
  path: '/sector/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vault': typeof VaultRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vault': typeof VaultRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vault': typeof VaultRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vault' | '/apps/$appId' | '/sector/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vault' | '/apps/$appId' | '/sector/$slug'
  id: '__root__' | '/' | '/vault' | '/apps/$appId' | '/sector/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VaultRoute: typeof VaultRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  SectorSlugRoute: typeof SectorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$slug': {
      id: '/sector/$slug'
      path: '/sector/$slug'
      fullPath: '/sector/$slug'
      preLoaderRoute: typeof SectorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VaultRoute: VaultRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  SectorSlugRoute: SectorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
